### ISSUE TITLE
GLSL 3.30 is not supported / this renderer requires atleast OpenGL 3.2.

### ISSUE THREAD

**Issue by deepdad** [CoppeliaRobotics/CoppeliaSimLib#12]
Hi I need your help / advice for this:
Running an [example from somewhere](https://github.com/stepjam/RLBench) in python,

"0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES\n"  

and in the GUI:  

[simExtOpenGL3Renderer:error] this renderer requires atleast OpenGL 3.2. The version available is 2.1 Mesa 20.2.6

```bash
glxinfo | grep "OpenGL version"
OpenGL version string: 2.1 Mesa 20.2.6
```

**Comment by Coppelia** [comment]
Hi,
You have the Mesa OpenGL implementation installed, and a newer version or other implementation is required. Try to update your drivers, or use native drivers.
