### ISSUE TITLE
Not working when importing matplotlib.pyplot library

### ISSUE THREAD

**Issue by miquel-espinosa** [CoppeliaRobotics/CoppeliaSimLib#13]
Hi.

Just wanted to report a small bug. 
For some reason, Coppelia Simulator doesn't work when the library `matplotlib.pyplot` is imported. No idea why. 
In my particular case, I was using another library (`skfuzzy`) which imported _matplolib_ in one of its files.
By removing that import I was able to use the skfuzzy library correctly in the simulator.

Kind regards,

**Comment by Coppelia** [comment]
Hello,
Not sure I understand the context. In Which context does this happen? i.e. CoppeliaSimLib is not used with any Python item, whether in the same thread or same process. Currently only Python CoppeliaSim clients (e.g. via remote API) are supported

**Comment by miquel-espinosa** [comment]
Yeah, sorry I wasn't being very clear.
So, precisely, the bug appears when using Python via remote API with CoppeliaSim client.
If the python script imports `matplotlib.pyplot` library on the client side, coppelia simulation stops ejecution flow (without printing nor showing any error).

**Comment by miquel-espinosa** [comment]
I have checked with some of my colleges and they have not been able to reproduce such error. 
Specifically, I have checked with both a Linux and Mac, and they seem not to have this particular problem, everything running smoothly. I guess it is a problem with my local dependencies, specific to my machine. 

I am therefore closing the issue. Feel free to reopen if someone ever encountered such similar problem.
