### ISSUE TITLE
native M1 Arm version

### ISSUE THREAD

**Issue by siilats** [CoppeliaRobotics/CoppeliaSimLib#18]
Could we please get an M1 Arm version :) QT compiles on ARM already, would really help us out. Rosetta is slow.

**Comment by Coppelia** [comment]
@siilats, yes, we are working on that, hopefully within a few weeks

**Comment by candyriver** [comment]
Could we get an ARM version for Raspberry Pi 4 or other high-performance ARM boards just like RK3358?
