### ISSUE TITLE
Linked Dynamics/Mesh Plugins no longer appear to be available

### ISSUE THREAD

**Issue by drao2** [CoppeliaRobotics/CoppeliaSimLib#5]
The links in the README to additional plugins required for dynamics and mesh calculation don't appear to be valid. Are the plugins no longer required, or should the README instead link to eg. simExtDynamics and simExtOpenMesh?

**Comment by Coppelia** [comment]
Thanks for the info, and sorry for the very late reply. We are actually in the middle of very heavy rewrites and a few things have gone out of sync..
The referred plugins/repositories were for V-REP, with CoppeliaSim they have been replaced by [simExtGeometric](https://github.com/CoppeliaRobotics/simExtGeometric) and [simExtDynamics](https://github.com/CoppeliaRobotics/simExtDynamics).
