### ISSUE TITLE
Outdated source files in CMakeLists.txt

### ISSUE THREAD

**Issue by drao2** [CoppeliaRobotics/CoppeliaSimLib#6]
When trying to use cmake to generate a Makefile for the project, a number of the listed source files don't exist (eg. ui/qdlgscriptparameters.ui and ui/qdlginteractiveik.ui).

It looks as though the qmake files were updated for the V-REP --> CoppeliaSim transition [in this commit](https://github.com/CoppeliaRobotics/CoppeliaSimLib/commit/cf0e70e885600cf6e67c35706b7fbeb8fa60174d), but CMakeLists.txt appears to be the same as the initial.

Is cmake still supported? If the preference is to use qmake, then I think CMakeLists.txt should be removed.

**Comment by Coppelia** [comment]
Again sorry for the very late reply. We are actually in the middle of very heavy rewrites and a few things have gone out of sync.. and will remain like that for some time unfortunately. In the mean time, a few things will need to be manually adjusted / tweaked
