### ISSUE TITLE
Does not compile: symbol not found

### ISSUE THREAD

**Issue by piegamesde** [CoppeliaRobotics/CoppeliaSimLib#7]
When trying to compile, I get a lot of error like `error: ‘sim_appobj_constraintsolver_type’ was not declared in this scope; did you mean ‘sim_appobj_constraintsolver_type_old’?`. Apparently, these were deprecated (renamed) in the `include` repo a few commits ago, but not updated in here.###

**Comment by Coppelia** [comment]
Thank for mentioning this. We are in the middle of a very heavy rewrite, and a few repositories have gone out of sync. In the mean time you can either use the include folder from the current release, or rename that const in simCont.h
