### ISSUE TITLE
Image rendering speed

### ISSUE THREAD

**Issue by charleswilmot** [CoppeliaRobotics/CoppeliaSimLib#8]
Hello everyone,

First of all, thank you very much for the awesome work, we've been using VREP and CoppeliaSim for over a year at the university of Frankfurt and we're very happy with it.

We are doing reinforcement learning applied to 7DoF robotic arms (using pyrep), and we plan on integrating vision in our current approach. We however observed long rendering time, with FPS at around 20 for a 320x240 vision sensor.

My questions are the following: do you plan on investing time into optimizing rendering times? What is the current bottleneck in the image rendering process?

Best,
Charles

**Comment by Coppelia** [comment]
Hello Charles, the rendering times for the specified image size is indeed very low. It should be significantly higher. Is it possible that something else slows down CoppeliaSim? Or that you render several images in each simulation step, which would also explain such low FPS?
But yes, we are planning on switching to another rendering system
